### ISSUE TITLE
Version of the addon on the Godot asset library does not match the current master branch (Parser error upon running example scene)

### ISSUE THREAD

**Issue by git12121** [binogure-studio/chart-gd#6] opened 2021-08-10 17:01 UTC
OS: Windows 10
Godot Version: 3.3.2.stable
Plugin Version: 1.0.0 (version that's on the Godot asset library)

![image](https://user-images.githubusercontent.com/28541089/128902656-eba649e8-d782-44ba-aa59-f000db71c227.png)

**Comment by git12121** [comment] 2021-08-10 17:03
Turns out this was actually fixed in d30c57628e016877e51833c3c77836391f4d0802 but the Godot asset library version does not reflect this change

**Comment by xsellier** [comment] 2021-08-10 17:32
Duplicate of:
https://github.com/binogure-studio/chart-gd/issues/7

**Closed as completed by xsellier** 2021-08-10 17:32 UTC
Labels: duplicate
